version: "3.8"

services:
  managerapp-db:
    image: postgres:16
    container_name: managerapp-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - managerapp-db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data

  manager-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manager-server
    environment:
      - REDIS_URL=redis://cache:${REDIS_PORT}
      - POSTGRES_HOST=managerapp-db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MINIO_ENDPOINT=minio:9000
    ports:
      - ${MANAGER_SERVER_PORT}:3000
    depends_on:
      - managerapp-db
      - minio

volumes:
  managerapp-db-data:
